services:
  app:
    image: todo-frontend
    container_name: todo-frontend
    build:
      context: ./todo-frontend/
      dockerfile: Dockerfile
    environment:
        - VITE_BACKEND_URL=/api/

  nginx:
    image: nginx:1.29
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:90"

    container_name: reverse-proxy
    depends_on:
      - backend
      - app

  mongo:
    container_name: mongo_fullstack
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - ./todo-backend/mongo_data:/data/db

  redis:
    container_name: redis_fullstack
    image: redis
    volumes:
      - ./todo-backend/redis_data:/data
      - ./todo-backend/redis/redis.conf:/usr/local/etc/redis/redis.conf

  backend:
    container_name: todo-backend
    image: todo-backend
    build:
      context: ./todo-backend/
      dockerfile: Dockerfile
    environment:
      - REDIS_URL=redis://redis:6379
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
